import Head from 'next/head'
import Header from '../components/Header'
import LotteryEntrance from '../components/LotteryEntrance'


export default function Home() {
  return (
    <>
      <Head>
        <title>Lottery Smart Contract</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <h1>Hello</h1>
      <LotteryEntrance />
    </>
  )
}
